services:
  - type: web
    name: django-file-upload
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      mkdir -p media
    startCommand: gunicorn video.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: "True"
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: RENDER
        value: "1"
